In [1]:
import numpy as np
import pandas as pd

Merging 2 DataFrames

In [7]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['John','Anna','Peter','Linda','Bob'],
    'department': ['HR','IT','Finance','IT','HR']
})

salaries = pd.DataFrame({
    'employee_id': [1,2,3,9,10],
    'salary': [60000,65000,75000,80000,85000],
    'bonus': [5000,1000,7000,8000,12000]
})

In [8]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [9]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   65000   1000
2            3   75000   7000
3            9   80000   8000
4           10   85000  12000

In [11]:
pd.merge(employees, salaries, on = 'employee_id', how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   65000   1000
2            3  Peter    Finance   75000   7000

In [12]:
pd.merge(employees, salaries, on = 'employee_id', how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  65000.0   1000.0
2            3  Peter    Finance  75000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            9    NaN        NaN  80000.0   8000.0
6           10    NaN        NaN  85000.0  12000.0

In [13]:
pd.merge(employees, salaries, on = 'employee_id', how = 'left')

   employee_id   name department   salary   bonus
0            1   John         HR  60000.0  5000.0
1            2   Anna         IT  65000.0  1000.0
2            3  Peter    Finance  75000.0  7000.0
3            4  Linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN

In [14]:
pd.merge(employees, salaries, on = 'employee_id', how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   65000   1000
2            3  Peter    Finance   75000   7000
3            9    NaN        NaN   80000   8000
4           10    NaN        NaN   85000  12000

Concatination of 2 DataFrames

In [16]:
df1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B': ['B0','B1','B2'],
    'C': ['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B': ['B3','B4','B5'],
    'C': ['C3','C4','C5']
})

In [17]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [18]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [23]:
pd.concat([df1,df2]) #concatination based on columns

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [24]:
pd.concat([df1,df2], axis = 1) #concatination based on rows

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining 2 DataFrames

In [26]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
},index = [1,2,3])

df2 = pd.DataFrame({
    'score': [85,90,75]
},index = [1,2,3])

In [27]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [28]:
df2

   score
1     85
2     90
3     75

In [31]:
df1.join(df2)

      name  score
1    Alice     85
2      Bob     90
3  Charlie     75