In [2]:
import numpy as np
import pandas as pd

Finding Missing Data

In [8]:
data = {
    'A': [1,2,np.nan,4,5],
    'B': [np.nan,2,3,4,5],
    'C': [1,2,3,np.nan,np.nan],
    'D': [1,np.nan,np.nan,np.nan,5],
}
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [11]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [12]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [13]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing Missing Data- It works on the basis of rows

In [14]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [15]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [16]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [19]:
df.dropna(thresh = 3) #thresh = 3 means rows me 3 known values to hona hi chahiye

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

Filling Missing Data

In [20]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [24]:
values = {'A': 0 , 'B': 100, 'C': 200, 'D': 300}
df.fillna(value = values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  300.0
2  0.0    3.0    3.0  300.0
3  4.0    4.0  200.0  300.0
4  5.0    5.0  200.0    5.0

In [25]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0