Series is an one dimensional array with any type of data

Creation of Series-:
There are multiple ways to create a Series

In [24]:
import numpy as np
import pandas as pd

In [25]:
labels = ['a','b','c']
arr = np.array([1,2,3])
my_list = [11,22,33]
dict = {1:2, 2: 3, 3:4}

In [26]:
pd.Series(my_list)  #default labels Series

0    11
1    22
2    33
dtype: int64

pd.Series(my_list, index = labels)  #series created by list

In [27]:
pd.Series(arr, index = labels) #Series created by array

a    1
b    2
c    3
dtype: int64

In [28]:
pd.Series(dict)  #Series created by dictionary

1    2
2    3
3    4
dtype: int64

Data Frames:- it is a collection of multiple series

Creation of Data Frames:-

In [32]:
labels = [1,2,3,4]
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data, index = labels)
df

    Name  Age      City  Salary
1   John   28  New York   65000
2   Anna   34     Paris   70000
3  Peter   29    Berlin   62000
4  Linda   42    London   85000

In [73]:
data = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris', 70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
columns = ['Name' , 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data , columns = columns)
labels = [1,2,3,4]
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

In [74]:
df2['Name']  #single column selection

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [75]:
df2[['Name', 'City']] #selection of multiple columns

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creation of New Column

In [76]:
df2['Designation'] = ['Doctor','Engineer','Artist','Engineer']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Artist
3  Linda   42    London   85000    Engineer

Removing Columns

In [77]:
#df2.drop('Designation', axis = 1)  #drop main data se remove nhi karta hai bas ek idea deta hai ki aapka data kaisa dikhega remove karne ke baad

In [78]:
df2.drop('Designation', axis = 1 , inplace = True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [85]:
df2.drop(['City','Salary'], axis = 1) #multiple columns's removal

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [82]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [86]:
df2.drop(0, axis = 0) # Removal of row

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

Selecting Rows

In [90]:
df2.loc[0] # One row selection  or df2.iloc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [91]:
df2.loc[[0,1]] #multiple row selection

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

Selecting Subsets of Rows and Columns

In [93]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [95]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [99]:
#I only want to see those people whose age is above 30
df2[df2['Age'] > 30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [103]:
#I only want to see those people whose age is above 30 and from paris
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000